#!/usr/bin/python

try:
    import cPickle as pickle
except:
    import pickle

import matplotlib.pyplot as plt
import numpy as np
from fibte.trafficgen.flowGenerator import isElephant
from fibte import LINK_BANDWIDTH

"""
This module defines functions that extract statistics about the traffic files generated by the traffic generator.
"""

class TrafficStats(object):
    def __init__(self, filename):
        self.filename = filename
        self.params = self.get_traffic_params(self.filename)
        self.traffic_per_host = self.load_traffic_file()
        self.hosts = self.traffic_per_host.keys()
        self.collectAllStats()

    @staticmethod
    def get_traffic_params(filename):
        params = {'senders':[],'receivers':[],
                  'pmice':-1,'pelephant': -1,
                  'flow_rate': -1,
                  'total_time': -1,
                  'time_step': -1}
        slash_index = filename.find('/')
        traffic_filename = filename[slash_index+1:]
        traffic_filename = traffic_filename.split('.')[0]
        traffic_filename = traffic_filename.replace('_to', '')
        (senders, receivers, percents, rate, totaltime, timestep) = traffic_filename.split('_')
        params['senders'] = senders.split(',')
        params['receivers'] = receivers.split(',')
        (pmice, pelephant) = percents.split('e')
        params['pmice'] = float(pmice.replace('m', '').replace(',', '.'))
        params['pelephant'] = float(pelephant.replace(',', '.'))
        params['flow_rate'] = float(rate.strip('fr').replace(',', '.'))
        params['total_time'] = int(totaltime.strip('t'))
        params['time_step'] = int(timestep.strip('ts'))
        return params

    def load_traffic_file(self):
        traffic = pickle.load(open(self.filename,"r"))
        return traffic

    def get_last_flow_finish_time(self):
        """Returs the finish time of the last ending flow"""
        max_flow_finish_time = 0
        for (h, fl) in self.traffic_per_host.iteritems():
            for f in fl:
                start_time = f['start_time']
                duration = f['duration']
                end_time = start_time + duration
                if end_time > max_flow_finish_time:
                    max_flow_finish_time = end_time

        return max_flow_finish_time

    def flows_per_second(self):
        """
        Returns
        :param traffic:
        :return:
        """
        last_flow_end_time = int(self.get_last_flow_finish_time())
        self.traffic_per_second = {i: [] for i in range(0, last_flow_end_time+1)}
        for i in self.traffic_per_second.keys():
            fws = [f for h, fl in self.traffic_per_host.iteritems() for f in fl if f['start_time'] <= i and (f['start_time']+f['duration']) >= i]
            self.traffic_per_second[i] = fws

    def collectAllStats(self):
        self.flows_per_second()

    def get_flows_over_time_and_ratio(self):
        flows = []
        mice = []
        elephant = []
        for i, fws in self.traffic_per_second.iteritems():
            total_flows = len(fws)
            if total_flows != 0:
                flows.append(total_flows)
                e_count = len([f for f in fws if isElephant(f)])
                m_count = total_flows - e_count
                elephant.append(e_count/float(total_flows))
                mice.append(m_count/float(total_flows))
            else:
                flows.append(0)
                mice.append(0)
                elephant.append(0)
        return (flows, mice, elephant)

    def get_flows_over_time(self):
        flows = []
        mice = []
        elephant = []
        for i, fws in self.traffic_per_second.iteritems():
            total_flows = sum([f['size'] for f in fws])
            flows.append(total_flows)
            e_count = sum([f['size'] for f in fws if isElephant(f)])
            m_count = total_flows - e_count
            elephant.append(e_count)
            mice.append(m_count)
        return (flows, mice, elephant)

    def plot_flows_over_time(self):
        """
        Plots the number of flows per second, as well as the ratio of elephant and mice
        :return:
        """
        # Get data to plot
        (flows, mice, elephant) = self.get_flows_over_time_and_ratio()
        fig, ax1 = plt.subplots(figsize=(80, 20))
        fig.suptitle("Number of active flows over time", fontsize=20)
        plt.xlabel("Time (s)", fontsize=16)

        # Plot total number
        ax1.set_ylabel("Total number of flows", fontsize=16)
        ax1.plot(flows, color='black', label="total", linewidth=2.0)

        # Plot ratios
        ax2 = ax1.twinx()
        ax2.plot(mice, color='green', label='mice', linewidth=2.0)
        ax2.plot(elephant, color='blue', label='elephant', linewidth=2.0)

        ax2.set_ylabel('Elephant and Mice ratio', fontsize=16)

        # Write legend and plot
        plt.legend(loc='best')
        # Set grid on
        plt.grid(True)
        plt.show()

    def plot_traffic_over_time(self):
        # Get data to plot
        (flows, mice, elephant) = self.get_flows_over_time()
        fig, ax1 = plt.subplots(figsize=(80, 20))
        fig.suptitle("Total traffic in the network over time", fontsize=20)
        plt.xlabel("Time (s)", fontsize=16)

        # Plot total number
        ax1.set_ylabel("DC traffic", fontsize=16)
        ax1.plot(flows, color='black', label="total", linewidth=2.0)

        # Plot ratios
        ax1.plot(mice, color='green', label='mice', linewidth=2.0)
        ax1.plot(elephant, color='blue', label='elephant', linewidth=2.0)

        # Write legend and plot
        plt.legend(loc='best')
        # Set grid on
        plt.grid(True)
        plt.show()

    def get_average_host_load(self):
        """"""
        input_avg = []
        output_avg = []
        for (t, fws) in self.traffic_per_second.iteritems():
            host_traffic_in = {h: 0 for h in self.hosts}
            host_traffic_out = {h: 0 for h in self.hosts}
            # Collect per host
            for f in fws:
                host_traffic_in[f['src']] += f['size']
                host_traffic_out[f['dst']] += f['size']

            # Compute averages
            out_avg = np.asarray(host_traffic_out.values())
            in_avg = np.asarray(host_traffic_in.values())
            out_avg = out_avg.mean()
            in_avg = in_avg.mean()

            input_avg.append(in_avg)
            output_avg.append(out_avg)

        return (input_avg, output_avg)

    def plot_average_host_load(self):
        # Get data to plot
        (input, output) = self.get_average_host_load()
        fig, ax1 = plt.subplots(figsize=(80, 20))
        fig.suptitle("Average host load over time", fontsize=20)
        plt.xlabel("Time (s)", fontsize=16)

        # Plot total number
        ax1.set_ylabel("DC traffic", fontsize=16)
        ax1.plot(input, color='black', label="Input", linewidth=2.0)
        ax1.plot(output, color='green', label='Output', linewidth=2.0)

        # Write legend and plot
        plt.legend(loc='best')
        # Set grid on
        plt.grid(True)
        plt.show()

    def get_host_load(self, host):
        input_load = []
        output_load = []
        for (t, fws) in self.traffic_per_second.iteritems():
            tin_load = 0
            tout_load = 0
            # Collect per host
            for f in fws:
                if f['src'] == host:
                    tin_load += f['size']
                elif f['dst'] == host:
                    tout_load += f['size']

            input_load.append(tin_load)
            output_load.append(tout_load)

        input_load = np.asarray(input_load)
        output_load = np.asarray(output_load)

        return (input_load/LINK_BANDWIDTH, output_load/LINK_BANDWIDTH)

    def plot_host_load(self, host):
        # Get data to plot
        (input, output) = self.get_host_load(host)
        fig, ax1 = plt.subplots(figsize=(80, 20))
        fig.suptitle("Host load over time", fontsize=20)
        plt.xlabel("Time (s)", fontsize=16)

        # Plot total number
        ax1.set_ylabel("Host traffic", fontsize=16)
        ax1.plot(input, color='red', label="Input", linewidth=2.0)
        ax1.plot(output, color='green', label='Output', linewidth=2.0)

        # Write legend and plot
        plt.legend(loc='best')
        # Set grid on
        plt.grid(True)
        plt.show()

if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser()

    parser.add_argument('-f','--traffic_file',
                           help='load traffic from a file so it can be repeated',
                           default="")

    parser.add_argument('--node', help="Plot traffic observed at node links only. e.g: h_0_0", type=str, default=None)

    args = parser.parse_args()


    if args.traffic_file:
        ts = TrafficStats(args.traffic_file)
        if args.node:
            ts.plot_host_load(host=args.node)

#        ts.plot_flows_over_time()
#        ts.plot_traffic_over_time()
